In [422]:
import pandas as pd
import numpy as np

In [467]:
data = [{'color_code': '35#', 'warehouse': '9100', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 42, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 42, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 42, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 108, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 162, 'cut_qty': 5, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 108, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 2, 'style_code': '01229F176A', 'produce_quantity': 12, 'cut_qty': 0, 'picking_unit': 2, 'set_code': 'X007', 'factory_name': '华城制衣', 'size_name': 'XS'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 6, 'style_code': '01229F176A', 'produce_quantity': 24, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'X008', 'factory_name': '华城制衣', 'size_name': 'XL'}, {'color_code': '35#', 'warehouse': '9100', 'size_order': 7, 'style_code': '01229F176A', 'produce_quantity': 24, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'X009', 'factory_name': '华城制衣', 'size_name': 'XXL'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 42, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 42, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 42, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 108, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 162, 'cut_qty': 5, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 108, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 2, 'style_code': '01229F176A', 'produce_quantity': 12, 'cut_qty': 0, 'picking_unit': 2, 'set_code': 'X010', 'factory_name': '华城制衣', 'size_name': 'XS'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 6, 'style_code': '01229F176A', 'produce_quantity': 24, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'X011', 'factory_name': '华城制衣', 'size_name': 'XL'}, {'color_code': '59#', 'warehouse': '9100', 'size_order': 7, 'style_code': '01229F176A', 'produce_quantity': 24, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'X012', 'factory_name': '华城制衣', 'size_name': 'XXL'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 98, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 98, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 98, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 270, 'cut_qty': 8, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 396, 'cut_qty': 12, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 270, 'cut_qty': 8, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 2, 'style_code': '01229F176A', 'produce_quantity': 24, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'X007', 'factory_name': '华城制衣', 'size_name': 'XS'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 6, 'style_code': '01229F176A', 'produce_quantity': 72, 'cut_qty': 2, 'picking_unit': 2, 'set_code': 'X008', 'factory_name': '华城制衣', 'size_name': 'XL'}, {'color_code': '35#', 'warehouse': '9051', 'size_order': 7, 'style_code': '01229F176A', 'produce_quantity': 96, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'X009', 'factory_name': '华城制衣', 'size_name': 'XXL'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 98, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 98, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 98, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'I040', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 3, 'style_code': '01229F176A', 'produce_quantity': 270, 'cut_qty': 8, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'S'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 4, 'style_code': '01229F176A', 'produce_quantity': 396, 'cut_qty': 12, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'M'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 5, 'style_code': '01229F176A', 'produce_quantity': 270, 'cut_qty': 8, 'picking_unit': 2, 'set_code': 'SOLID', 'factory_name': '华城制衣', 'size_name': 'L'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 2, 'style_code': '01229F176A', 'produce_quantity': 24, 'cut_qty': 1, 'picking_unit': 2, 'set_code': 'X010', 'factory_name': '华城制衣', 'size_name': 'XS'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 6, 'style_code': '01229F176A', 'produce_quantity': 72, 'cut_qty': 2, 'picking_unit': 2, 'set_code': 'X011', 'factory_name': '华城制衣', 'size_name': 'XL'}, {'color_code': '59#', 'warehouse': '9051', 'size_order': 7, 'style_code': '01229F176A', 'produce_quantity': 96, 'cut_qty': 3, 'picking_unit': 2, 'set_code': 'X012', 'factory_name': '华城制衣', 'size_name': 'XXL'}]

In [468]:
size_order = sorted(list({(item['size_name'], item['size_order']) for item in data}), key=lambda x: x[1])
size_order = [i[0] for i in size_order]
size_order

['XS', 'S', 'M', 'L', 'XL', 'XXL']

In [469]:
import json
json_df = pd.read_json(json.dumps(data))

In [470]:
json_df

,color_code,cut_qty,factory_name,picking_unit,produce_quantity,set_code,size_name,size_order,style_code,warehouse
0,35#,1,华城制衣,2,42,I040,S,3,01229F176A,9100
1,35#,1,华城制衣,2,42,I040,M,4,01229F176A,9100
2,35#,1,华城制衣,2,42,I040,L,5,01229F176A,9100
3,35#,3,华城制衣,2,108,SOLID,S,3,01229F176A,9100
4,35#,5,华城制衣,2,162,SOLID,M,4,01229F176A,9100
5,35#,3,华城制衣,2,108,SOLID,L,5,01229F176A,9100
6,35#,0,华城制衣,2,12,X007,XS,2,01229F176A,9100
7,35#,1,华城制衣,2,24,X008,XL,6,01229F176A,9100
8,35#,1,华城制衣,2,24,X009,XXL,7,01229F176A,9100
9,59#,1,华城制衣,2,42,I040,S,3,01229F176A,9100
10,59#,1,华城制衣,2,42,I040,M,4,01229F176A,9100
11,59#,1,华城制衣,2,42,I040,L,5,01229F176A,9100
12,59#,3,华城制衣,2,108,SOLID,S,3,01229F176A,9100
13,59#,5,华城制衣,2,162,SOLID,M,4,01229F176A,9100
14,59#,3,华城制衣,2,108,SOLID,L,5,01229F176A,9100
15,59#,0,华城制衣,2,12,X010,XS,2,01229F176A,9100
16,59#,1,华城制衣,2,24,X011,XL,6,01229F176A,9100
17,59#,1,华城制衣,2,24,X012,XXL,7,01229F176A,9100
18,35#,3,华城制衣,2,98,I040,S,3,01229F176A,9051
19,35#,3,华城制衣,2,98,I040,M,4,01229F176A,9051
20,35#,3,华城制衣,2,98,I040,L,5,01229F176A,9051
21,35#,8,华城制衣,2,270,SOLID,S,3,01229F176A,9051
22,35#,12,华城制衣,2,396,SOLID,M,4,01229F176A,9051
23,35#,8,华城制衣,2,270,SOLID,L,5,01229F176A,9051
24,35#,1,华城制衣,2,24,X007,XS,2,01229F176A,9051
25,35#,2,华城制衣,2,72,X008,XL,6,01229F176A,9051
26,35#,3,华城制衣,2,96,X009,XXL,7,01229F176A,9051
27,59#,3,华城制衣,2,98,I040,S,3,01229F176A,9051
28,59#,3,华城制衣,2,98,I040,M,4,01229F176A,9051
29,59#,3,华城制衣,2,98,I040,L,5,01229F176A,9051
30,59#,8,华城制衣,2,270,SOLID,S,3,01229F176A,9051
31,59#,12,华城制衣,2,396,SOLID,M,4,01229F176A,9051
32,59#,8,华城制衣,2,270,SOLID,L,5,01229F176A,9051
33,59#,1,华城制衣,2,24,X010,XS,2,01229F176A,9051
34,59#,2,华城制衣,2,72,X011,XL,6,01229F176A,9051
35,59#,3,华城制衣,2,96,X012,XXL,7,01229F176A,9051

In [427]:
new_df1 = pd.pivot_table(json_df, 
                        values=['produce_quantity'],
                        index=['color_code', 'warehouse', 'set_code'],
                        columns=['size_name'],
                        fill_value=0,
                        aggfunc=np.sum,
                        dropna=True)

In [428]:
new_df1

                              produce_quantity                               \
size_name                                  3XL     L     M     S    XL   XS
color_code warehouse set_code
09#        9100      F010                    0  3036  4048  3036  2024    0
                     SOLID                   0  4296  4968  3720  3168    0
69#        9051      I007                    0   375   500   375   250    0
                     N005                    0     0     0   312     0    0
                     N006                    0     0   408     0     0    0
                     N007                    0   288     0     0     0    0
                     N008                    0     0     0     0   168    0
                     X004                    0     0     0     0     0  288
                     X005                    0     0     0     0     0    0
                     X006                  192     0     0     0     0    0
           9100      SOLID                   0  2208  2856  2208     0    0


size_name                      XXL
color_code warehouse set_code
09#        9100      F010        0
                     SOLID       0
69#        9051      I007        0
                     N005        0
                     N006        0
                     N007        0
                     N008        0
                     X004        0
                     X005      192
                     X006        0
           9100      SOLID       0

In [429]:
new_df1.columns
df1 = new_df1.reindex(columns=size_order, level='size_name')
df1

                              produce_quantity                               \
size_name                                   XS     S     M     L    XL  XXL
color_code warehouse set_code
09#        9100      F010                    0  3036  4048  3036  2024    0
                     SOLID                   0  3720  4968  4296  3168    0
69#        9051      I007                    0   375   500   375   250    0
                     N005                    0   312     0     0     0    0
                     N006                    0     0   408     0     0    0
                     N007                    0     0     0   288     0    0
                     N008                    0     0     0     0   168    0
                     X004                  288     0     0     0     0    0
                     X005                    0     0     0     0     0  192
                     X006                    0     0     0     0     0    0
           9100      SOLID                   0  2208  2856  2208     0    0


size_name                      3XL
color_code warehouse set_code
09#        9100      F010        0
                     SOLID       0
69#        9051      I007        0
                     N005        0
                     N006        0
                     N007        0
                     N008        0
                     X004        0
                     X005        0
                     X006      192
           9100      SOLID       0

In [430]:
# pd.concat([new_df1, new_df2], join="inner")
# new_df = new_df1.append(df2)
new_table = pd.concat([
                d.append(d.sum().rename(('', '加裁', '')))
                for k, d in df1.groupby(level=['color_code', 'warehouse'])
            ])
# new_table = pd.concat([
#                 d.append(x)
#                 for k, d in df1.groupby(level='color_code')
#             ])
# df1.dtypes
# df1.append(x)

In [431]:
new_table.loc[('', '加裁', '')] = new_table.loc[('', '加裁', '')] * 0.03
new_table.loc[('', '加裁', '')]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2817: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.

                              produce_quantity                          \
size_name                                   XS       S       M       L
color_code warehouse set_code
           加裁                             0.00  202.68  270.48  219.96
                                          8.64   20.61   27.24   19.89
                                          0.00   66.24   85.68   66.24


size_name                          XL   XXL   3XL
color_code warehouse set_code
           加裁                  155.76  0.00  0.00
                                12.54  5.76  5.76
                                 0.00  0.00  0.00

In [432]:
new_table.loc[:] = round(new_table.loc[:])
new_table.loc[:] = new_table.loc[:].astype('int64')
new_table

                              produce_quantity                               \
size_name                                   XS     S     M     L    XL  XXL
color_code warehouse set_code
09#        9100      F010                    0  3036  4048  3036  2024    0
                     SOLID                   0  3720  4968  4296  3168    0
           加裁                                0   203   270   220   156    0
69#        9051      I007                    0   375   500   375   250    0
                     N005                    0   312     0     0     0    0
                     N006                    0     0   408     0     0    0
                     N007                    0     0     0   288     0    0
                     N008                    0     0     0     0   168    0
                     X004                  288     0     0     0     0    0
                     X005                    0     0     0     0     0  192
                     X006                    0     0     0     0     0    0
           加裁                                9    21    27    20    13    6
69#        9100      SOLID                   0  2208  2856  2208     0    0
           加裁                                0    66    86    66     0    0


size_name                      3XL
color_code warehouse set_code
09#        9100      F010        0
                     SOLID       0
           加裁                    0
69#        9051      I007        0
                     N005        0
                     N006        0
                     N007        0
                     N008        0
                     X004        0
                     X005        0
                     X006      192
           加裁                    6
69#        9100      SOLID       0
           加裁                    0

In [433]:
new_table = new_table.append(new_table.sum().rename(('合计', '', '')))
new_table[('produce_quantity', '合计')] = new_table.sum(axis=1)
new_table

                              produce_quantity                                 \
size_name                                   XS     S      M      L    XL  XXL
color_code warehouse set_code
09#        9100      F010                    0  3036   4048   3036  2024    0
                     SOLID                   0  3720   4968   4296  3168    0
           加裁                                0   203    270    220   156    0
69#        9051      I007                    0   375    500    375   250    0
                     N005                    0   312      0      0     0    0
                     N006                    0     0    408      0     0    0
                     N007                    0     0      0    288     0    0
                     N008                    0     0      0      0   168    0
                     X004                  288     0      0      0     0    0
                     X005                    0     0      0      0     0  192
                     X006                    0     0      0      0     0    0
           加裁                                9    21     27     20    13    6
69#        9100      SOLID                   0  2208   2856   2208     0    0
           加裁                                0    66     86     66     0    0
合计                                         297  9941  13163  10509  5779  198


size_name                      3XL     合计
color_code warehouse set_code
09#        9100      F010        0  12144
                     SOLID       0  16152
           加裁                    0    849
69#        9051      I007        0   1500
                     N005        0    312
                     N006        0    408
                     N007        0    288
                     N008        0    168
                     X004        0    288
                     X005        0    192
                     X006      192    192
           加裁                    6    102
69#        9100      SOLID       0   7272
           加裁                    0    218
合计                             198  40085

In [434]:
new_table1 = new_table.copy(deep=True)
new_table1.columns = new_table1.columns.droplevel(0)
new_table1

size_name                       XS     S      M      L    XL  XXL  3XL     合计
color_code warehouse set_code
09#        9100      F010        0  3036   4048   3036  2024    0    0  12144
                     SOLID       0  3720   4968   4296  3168    0    0  16152
           加裁                    0   203    270    220   156    0    0    849
69#        9051      I007        0   375    500    375   250    0    0   1500
                     N005        0   312      0      0     0    0    0    312
                     N006        0     0    408      0     0    0    0    408
                     N007        0     0      0    288     0    0    0    288
                     N008        0     0      0      0   168    0    0    168
                     X004      288     0      0      0     0    0    0    288
                     X005        0     0      0      0     0  192    0    192
                     X006        0     0      0      0     0    0  192    192
           加裁                    9    21     27     20    13    6    6    102
69#        9100      SOLID       0  2208   2856   2208     0    0    0   7272
           加裁                    0    66     86     66     0    0    0    218
合计                             297  9941  13163  10509  5779  198  198  40085

In [435]:
table_df = pd.DataFrame(new_table1.to_records())
num = 14 - len(table_df.columns) - 1
list1 = ['color_code', 'warehouse', 'set_code']
col_list = list1 + [''] + size_order + ['']*num + ['合计']
len(col_list)
table_df = table_df.reindex(columns=list1+['']+size_order+['']*num+['合计'])
table_df

,color_code,warehouse,set_code,,XS,S,M,L,XL,XXL,3XL,,,合计
0,09#,9100,F010,NaN,0,3036,4048,3036,2024,0,0,NaN,NaN,12144
1,09#,9100,SOLID,NaN,0,3720,4968,4296,3168,0,0,NaN,NaN,16152
2,,加裁,,NaN,0,203,270,220,156,0,0,NaN,NaN,849
3,69#,9051,I007,NaN,0,375,500,375,250,0,0,NaN,NaN,1500
4,69#,9051,N005,NaN,0,312,0,0,0,0,0,NaN,NaN,312
5,69#,9051,N006,NaN,0,0,408,0,0,0,0,NaN,NaN,408
6,69#,9051,N007,NaN,0,0,0,288,0,0,0,NaN,NaN,288
7,69#,9051,N008,NaN,0,0,0,0,168,0,0,NaN,NaN,168
8,69#,9051,X004,NaN,288,0,0,0,0,0,0,NaN,NaN,288
9,69#,9051,X005,NaN,0,0,0,0,0,192,0,NaN,NaN,192
10,69#,9051,X006,NaN,0,0,0,0,0,0,192,NaN,NaN,192
11,,加裁,,NaN,9,21,27,20,13,6,6,NaN,NaN,102
12,69#,9100,SOLID,NaN,0,2208,2856,2208,0,0,0,NaN,NaN,7272
13,,加裁,,NaN,0,66,86,66,0,0,0,NaN,NaN,218
14,合计,,,NaN,297,9941,13163,10509,5779,198,198,NaN,NaN,40085

In [436]:
table_df = table_df.replace(np.nan,' ', regex=True)
table_df

,color_code,warehouse,set_code,,XS,S,M,L,XL,XXL,3XL,,,合计
0,09#,9100,F010,,0,3036,4048,3036,2024,0,0,,,12144
1,09#,9100,SOLID,,0,3720,4968,4296,3168,0,0,,,16152
2,,加裁,,,0,203,270,220,156,0,0,,,849
3,69#,9051,I007,,0,375,500,375,250,0,0,,,1500
4,69#,9051,N005,,0,312,0,0,0,0,0,,,312
5,69#,9051,N006,,0,0,408,0,0,0,0,,,408
6,69#,9051,N007,,0,0,0,288,0,0,0,,,288
7,69#,9051,N008,,0,0,0,0,168,0,0,,,168
8,69#,9051,X004,,288,0,0,0,0,0,0,,,288
9,69#,9051,X005,,0,0,0,0,0,192,0,,,192
10,69#,9051,X006,,0,0,0,0,0,0,192,,,192
11,,加裁,,,9,21,27,20,13,6,6,,,102
12,69#,9100,SOLID,,0,2208,2856,2208,0,0,0,,,7272
13,,加裁,,,0,66,86,66,0,0,0,,,218
14,合计,,,,297,9941,13163,10509,5779,198,198,,,40085

In [438]:
table_df[['warehouse', '合计']]

   warehouse     合计
0       9100  12144
1       9100  16152
2         加裁    849
3       9051   1500
4       9051    312
5       9051    408
6       9051    288
7       9051    168
8       9051    288
9       9051    192
10      9051    192
11        加裁    102
12      9100   7272
13        加裁    218
14            40085

In [450]:
x= sum(table_df.loc[table_df['warehouse']=='加裁', '合计'])
x

1169

In [454]:
# y = sum(table_df.loc[table_df['warehouse']!='加裁', '合计'])
# y

In [452]:
x + y

80170

In [456]:
table_df.iloc[-1,-1]

40085

In [411]:
a = table_df.to_numpy().tolist()
a

[['09#',
  '9100',
  'F010',
  ' ',
  0,
  3036,
  4048,
  3036,
  2024,
  0,
  0,
  ' ',
  ' ',
  12144],
 ['09#',
  '9100',
  'SOLID',
  ' ',
  0,
  3720,
  4968,
  4296,
  3168,
  0,
  0,
  ' ',
  ' ',
  16152],
 ['', '加裁', '', ' ', 0, 203, 270, 220, 156, 0, 0, ' ', ' ', 849],
 ['69#', '9051', 'I007', ' ', 0, 375, 500, 375, 250, 0, 0, ' ', ' ', 1500],
 ['69#', '9051', 'N005', ' ', 0, 312, 0, 0, 0, 0, 0, ' ', ' ', 312],
 ['69#', '9051', 'N006', ' ', 0, 0, 408, 0, 0, 0, 0, ' ', ' ', 408],
 ['69#', '9051', 'N007', ' ', 0, 0, 0, 288, 0, 0, 0, ' ', ' ', 288],
 ['69#', '9051', 'N008', ' ', 0, 0, 0, 0, 168, 0, 0, ' ', ' ', 168],
 ['69#', '9051', 'X004', ' ', 288, 0, 0, 0, 0, 0, 0, ' ', ' ', 288],
 ['69#', '9051', 'X005', ' ', 0, 0, 0, 0, 0, 192, 0, ' ', ' ', 192],
 ['69#', '9051', 'X006', ' ', 0, 0, 0, 0, 0, 0, 192, ' ', ' ', 192],
 ['', '加裁', '', ' ', 9, 21, 27, 20, 13, 6, 6, ' ', ' ', 102],
 ['69#', '9100', 'SOLID', ' ', 0, 2208, 2856, 2208, 0, 0, 0, ' ', ' ', 7272],
 ['', '加裁', '', ' ', 0, 66, 86, 66, 0, 0, 0, ' ', ' ', 218],
 ['合计', '', '', ' ', 297, 9941, 13163, 10509, 5779, 198, 198, ' ', ' ', 40085]]